name: My-GitHub-Actions
env:
  APPLICATION_NAME       : "Flask"
  DEPLOY_PACKAGE_NAME    : "flask_deploy_ver-${{ github.sha }}"

on:
  push:
    branches:
      - main 

jobs:

  my_testing:
    runs-on: ubuntu-latest
    steps:
        - name: Print Hello message
          run : echo "Hello world from Testing job"
          
        - name: Execute few commands
          run : |
            echo "Hello Message1"
            echo "Hello Message2"
            echo "Application name: ${{ env.APPLICATION_NAME }}"
            
        - name: "Git clone"
          uses : actions/checkout@v3
        
        - name: List folder content
          run : ls -la
   
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1 : "Variable_1"
      VAR2 : "Variable_2"
    
    steps:
       - name: Print Hello message
         run : |
            echo "var1 = ${{ env.VAR1 }}"
            echo "var2 = ${{ env.VAR2 }}"
            echo "var3 = $local_var"
         env:
           local_var: "This is local var"
     
       - name: Print Hello message
         run : echo "Hello world from Deploy job" 
         
       
       - name: Printing Deployment message
         run : echo "Deploy Package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
 
       - name: zip
         run : zip --version
