- name: GitHub yamllint check
  # You may pin to the exact commit or the version.
  # uses: koozz/yamllint-action@4bbfdfba89ec38a56af88e7288c89f4f3a635463
  uses: koozz/yamllint-action@1.0.0


name: My-GitHub-Actions

on:
  push:
    branches:
      - main 

jobs:

my_testing:
runs_on: ubuntu-latest
steps:
- name: Print Hello message
run: echo "Hello world from Testing job"
   
my_deploy:
runs_on: ubuntu-latest
steps:
- name: Print Hello message
run: echo "Hello world from Testing job" 
 
