name: My-GitHub-Actions

on:
  push:
    branches:
      - main 

jobs:

  my_testing:
    runs-on: ubuntu-latest
    steps:
        - name: Print Hello message
          run : echo "Hello world from Testing job"
   
  my_deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Print Hello message
         run : echo "Hello world from Testing job" 
 
